apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: python-ayvgxagw 
  janus-idp.io/tekton: python-ayvgxagw
  backstage.io/kubernetes-id: python-ayvgxagw
  backstage.io/kubernetes-namespace: deploy-app 
  app.kubernetes.io/part-of: python-ayvgxagw
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml